---
# handlers file for teamspeak

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart TeamSpeak 3 Server
  service:
    name: teamspeak3-server
    state: restarted

- name: Prune older TeamSpeak 3 Server versions
  shell: "{{ item }}"
  with_items:
    - find {{ teamspeak.home }}/teamspeak3-server_linux_amd64-* -maxdepth 0 -type d | sort -V | head -n-{{ teamspeak.keep }} | xargs echo rm -rf
    - find {{ teamspeak.home }}/teamspeak3-server_linux_amd64-*.tar.bz2 -type f | sort -V | head -n-{{ teamspeak.keep }} | xargs rm -f
